####### 用户操作


###
POST http://localhost:10080/api/users/make/admin
Content-Type: application/json;charset=utf8
Authorization:Basic dGVzdDoyMzMz
# 注册必须提供手机号phoneNumber和密码password,默认权限为注册用户,
# 注册管理员 投到/api/users/make/admin下面
# 注册前台 投到/api/users/make/employee下面

{
  "phoneNumber": "18800000002",
  "password": "2333",
  "nickname": "昵称"
}
###
POST http://localhost:10080/api/users/make
Content-Type: application/json;charset=utf8

{
  "phoneNumber": "12345478912",
  "password": "2333",
  "nickname": "的4rq34re",
  "register_date": "2016-03-16T13:56:39.492"
}
###
POST http://localhost:10080/api/restful/users
Content-Type: application/json;charset=utf8
#Authorization:Basic dGVzdDoyMzMz
# 这是注册的后台接口,以后会关闭,注意使用phoneNumber

{
  "role": "注册用户",
  "password": "2333",
  "nickname": "的4rq34re",
  "phoneNumber": "12345478911",
  "register_date": "2016-03-16T13:56:39.492"
}

###
POST http://localhost:10080/api/users/login
Content-Type: application/json;charset=utf8
Authorization:Basic dGVzdDoyMzMz
# 登录提供手机号和密码,返回用户信息

{
  "phoneNumber": "18800000001",
  "password": "2333"
}
###
GET http://localhost:10080/api/users/dummy

###
GET http://localhost:10080/api/users/guests?phone=12345678888
# 找出用户绑定的身份证

###
GET http://localhost:10080/api/users/transactions?phone=18800000001
Content-Type: application/json
Authorization:Basic dGVzdDoyMzMz

{
  "identification":"130622199901017537",
  "name":"宋娘"
}



###### 房间操作

###
POST http://localhost:10080/api/restful/roomTypes/
Content-Type: application/json
# 添加房间类型的后台接口 不推荐使用,重复返回409

{
  "type": "官方",
  "description": "估读法"
}
###
POST http://localhost:10080/api/rooms/addType/
Content-Type: application/json
# 添加房间类型的正式接口,重复返回409

{
  "type": "官方2",
  "description": "估读法"
}

###
POST http://localhost:10080/api/transactions/make
Content-Type: application/json

{
  "dateFrom": "2017-12-22T16:57:10",
  "dateTo": "2017-12-23T16:57:10",
  "phone": "18800000001",
  "guests": [
    "130622199901017537"
  ],
  "room": {
    "floor": 1,
    "number": 1
  }
}
###
GET http://localhost:10080/api/transactions/list
###
GET http://localhost:10080/api/rooms/list?priceFrom=100
###
GET http://localhost:10080/api/rooms/list?priceFrom=99&priceTo=100
# [99, 100]
###
POST http://localhost:10080/api/transactions/make
Content-Type: application/json

{
  "create_date": "2017-12-22T16:57:10",
  "dateFrom": "2017-12-22T16:57:10",
  "dateTo": "2017-12-23T16:57:10",
  "activated": false,
  "used": false
}
###
POST http://localhost:10080/api/users/make
Content-Type: application/json

{
  "phoneNumber": "18800000003",
  "password": "2333",
  "nickname": "三娃"
}
###
POST http://localhost:10080/api/users/guests?phone=18800000001
Content-Type: application/json
Authorization:Basic dGVzdDoyMzMz

{
  "identification":"111111200001013335",
  "name":"宋三娘"
}

###
GET http://localhost:10080/api/transactions/list

###
POST http://localhost:10080/api/users/guests?phone=18800000001
Content-Type: application/json
Authorization:Basic dGVzdDoyMzMz

{
  "identification":"130622199901017338",
  "name":"宋三娘"
}

###
GET http://localhost:10080/api/rooms
###
PUT http://localhost:10080/api/rooms?floor=
Content-Type: application/json

{
  "nickname": "新昵称",
  "password": "23333"
}
###
GET http://localhost:10080/api/users?phone=18800000001
###
GET http://localhost:10080/api/users/guests?phone=18800000001
###
POST http://localhost:10080/api/rooms/add
Content-Type: application/json

{
  "type":"大床房",
  "direction":"东",
  "specialty":"一个介绍",
  "price":"1233",
  "roomNumber": {
        "floor": 1,
        "number": 45
      }
}

###
POST http://localhost:10080/api/rooms/add
Content-Type: application/json

{
    "roomNumber": {
      "floor": 3,
      "number": 1
    },
    "type":"http://localhost:10080/api/restful/roomTypes/3",
    "direction": "http://localhost:10080/api/restful/roomDirections/2",
    "specialty": "141234",
    "price": 101
 }
###
POST http://localhost:10080/api/rooms/add
Content-Type: application/json

{
  "type": "大床房",
  "direction": "东",
  "specialty": "一个介绍",
  "price": "143",
  "roomNumber": {
    "floor": 3,
    "number": 1
  }
}

###
GET http://localhost:10080/api/rooms/list?priceFrom=100&type=大床房&direction=东&from=2017-12-27T16:57:10

###
GET http://localhost:10080/api/users/transactions?phone=18800000001

###
POST http://localhost:10080/api/rooms/types
Content-Type: application/json
Authorization:Basic dGVzdDoyMzMz

{
  "type": "大床房",
  "description": "冬暖夏狼"
}


###
POST http://localhost:10080/api/rooms/control?floor=1&number=3
Content-Type: application/json

{
  "type": "东2",
  "description": "冬暖夏狼"
}

###
POST http://localhost:10080/api/rooms/control?floor=5&number=1
Content-Type: application/json

{
  "type": "东2",
  "description": "冬暖夏狼"
}
###
GET http://localhost:10080/api/rooms/load
Content-Type: application/json

{
  "type": "东2",
  "description": "冬暖夏狼"
}

###
POST http://localhost:10080/api/rooms/types
Content-Type: application/json
Authorization:Basic dGVzdDoyMzMz

{
  "type": "大床房",
  "description": "足够两个人唑在一起的大小"
}
###
POST http://localhost:10080/api/rooms/directions
Content-Type: application/json

{
  "type": "东方",
  "description": "车万"
}

###
PUT http://localhost:10080/api/rooms/types?type=大床房
Content-Type: application/json

{
  "description": "修改之后的内容"
}

###
GET http://localhost:10080/api/users/get?phone=18888888888
###
GET http://localhost:10080/api/users/guests?phone=18834321240
###
POST http://localhost:10080/api/users/guests?phone=18916961896
Content-Type: application/json

{
  "identification": "13062219990101753545",
  "name": "宋娘2"
}
###
GET http://localhost:10080/api/rooms

###
GET http://localhost:10080/api/rooms/load2

###
POST http://localhost:10080/api/rooms
Content-Type: application/json

{
  "type": "大床房",
  "direction": "东方",
  "specialty": "小房间",
  "price": "123",
  "roomNumber": {
    "floor": 1,
    "number": 4
  },
  "broken":true
}

###
GET http://localhost:10080/api/rooms/directions

###
POST http://localhost:10080/api/rooms/directions
###
DELETE http://localhost:10080/api/rooms/directions?direction=大床房

###
POST http://localhost:10080/api/users/make/admin
Content-Type: application/json

{
  "phoneNumber": "18888888888",
  "password": "2333",
  "nickname": "老子最大"
}
###
POST http://localhost:10080/api/users/make/employee
Content-Type: application/json

{
  "phoneNumber": "17788888888",
  "password": "2333",
  "nickname": "前台小姐姐"
}

###
GET http://localhost:10080/api/users/

###
POST http://localhost:10080/api/transactions
Content-Type: application/json

{
  "dataFrom": "2017-12-22T16:57:10",
  "dataTo": "2017-12-23T16:57:10",
  "phone": "18800000001",
  "guests": [
    "111111200001013333", "111111200001013334"
  ],
  "room": {
    "floor": 1,
    "number": 1
  }
}

###
GET http://localhost:10080/api/users/transactions?phone=18888888888
Content-Type: application/json
Authorization: Basic MTg4ODg4ODg4ODg6MjMzMw==

{

}

###
GET http://localhost:10080/api/comments/room?roomId=8
###
GET http://localhost:10080/api/comments/transaction??transactionId=1
###
POST http://localhost:10080/api/comments/?transactionId=1
Content-Type: application/json

{
"body":"abc"
}

###
PATCH https://enihsyou.synology.me:8899/api/users?phone=10000000000
content-type:application/json;charset=UTF-8
authorization:Basic MTAwMDAwMDAwMDA6dW5kZWZpbmVk

{"nickname":"123"}

###
POST http://localhost:10080/api/transactions/checkout?bookId=3

###
